# Generated by Django 3.0.5 on 2023-12-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='White',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=135)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
