# Generated by Django 3.0.5 on 2023-12-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0002_white'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
