# Generated by Django 3.0.5 on 2023-12-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='description',
        ),
    ]
