# Generated by Django 3.0.5 on 2023-12-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0004_auto_20231213_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
